### ISSUE TITLE
Nested Panes Without Content

### ISSUE THREAD

**Issue by calebeno** [LukaszWatroba/v-accordion#19]
I'm working on a navigation menu using nested panes.  The top level works just fine, I have a nested accordion within that.  However, I do not have content for the nested layer.  Because of this, even though it works perfectly, I'm getting two errors in the console window.  One complains that the v-pane-content directive is not present.  The other complains that it cannot read 'toggle' of undefined, presumably referring to the missing directive.

It would be nice to be able to add in subpanes that did not require content.

Code:
```javascript
<v-accordion class="vAccordion--default" id="chapterBox">
	<v-pane ng-repeat="part in chapters" expanded="$first">
		<v-pane-header>
			{{ part.header }}
		</v-pane-header>
		<v-pane-content>
			<v-accordion ng-if="part.subpanes">
				<v-pane ng-repeat="chapter in part.subpanes">
					<v-pane-header>
						{{ chapter.header }}
					</v-pane-header>
				</v-pane>
			</v-accordion>
		</v-pane-content>
	</v-pane>
</v-accordion>
```

Errors:
```
Error: The `v-pane-content` directive can't be found
    at link (http://localhost:1337/app/bower_components/v-accordion/dist/v-accordion.js:372:15)
    at http://localhost:1337/app/bower_components/angular/angular.js:8740:44
    at invokeLinkFn (http://localhost:1337/app/bower_components/angular/angular.js:8746:9)
    at nodeLinkFn (http://localhost:1337/app/bower_components/angular/angular.js:8246:11)
    at compositeLinkFn (http://localhost:1337/app/bower_components/angular/angular.js:7637:13)
    at publicLinkFn (http://localhost:1337/app/bower_components/angular/angular.js:7512:30)
    at $get.boundTranscludeFn (http://localhost:1337/app/bower_components/angular/angular.js:7656:16)
    at controllersBoundTransclude (http://localhost:1337/app/bower_components/angular/angular.js:8273:18)
    at ngRepeatAction (http://localhost:1337/app/bower_components/angular/angular.js:27304:15)
    at Object.$watchCollectionAction [as fn] (http://localhost:1337/app/bower_components/angular/angular.js:15618:13) <v-pane ng-repeat="chapter in part.subpanes" class="ng-scope ng-isolate-scope">
```
```
TypeError: Cannot read property 'toggle' of undefined
    at PaneDirectiveController.ctrl.toggle (v-accordion.js:466)
    at v-accordion.js:307
    at Scope.$get.Scope.$eval (angular.js:15916)
    at Scope.$get.Scope.$apply (angular.js:16016)
    at HTMLElement.<anonymous> (v-accordion.js:306)
    at HTMLElement.jQuery.event.dispatch (jquery.js:4435)
    at HTMLElement.jQuery.event.add.elemData.handle (jquery.js:4121)
```

**Comment by LukaszWatroba** [comment]
Hey. I'm wondering why you don't use the regular `ul` tag, like so:

```html
<v-accordion class="vAccordion--default" id="chapterBox">
    <v-pane ng-repeat="part in chapters" expanded="$first">
        <v-pane-header>
            {{ part.header }}
        </v-pane-header>
        <v-pane-content>
            <ul ng-if="part.subpanes">
                <li ng-repeat="chapter in part.subpanes">
                    {{ chapter.header }}
                </li>
            </ul>
        </v-pane-content>
    </v-pane>
</v-accordion>
```

**Comment by calebeno** [comment]
Wow.  See, this, this right here is a classic example of trying to overthink your problem.  Cheers mate.  Also, thanks for writing this package.  It's been a huge help.

**Comment by nikhilpatteri** [comment]
I am also facing the same issue which is mentioned by Calebeno. 
But, I was using multiple v-pane tags inside v-accordion, and the error is similar as above. The requirement is like that where I have to repeat the data from multiple ng-repeats in the same accordion level.
