### ISSUE TITLE
gulp-sass and libsass binding

### ISSUE THREAD

**Issue by Zensey** [LukaszWatroba/v-accordion#35]
When I run gulp  I get the following error

```
/home/zensey/IdeaProjects/GitHub/v-accordion/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22
    throw new Error('`libsass` bindings not found. Try reinstalling `node-sass`?');
    ^

Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/home/zensey/IdeaProjects/GitHub/v-accordion/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/home/zensey/IdeaProjects/GitHub/v-accordion/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:430:26)
    at Object.Module._extensions..js (module.js:448:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/zensey/IdeaProjects/GitHub/v-accordion/node_modules/gulp-sass/index.js:3:17)
    at Module._compile (module.js:430:26)
zensey@pc:~/IdeaProjects/GitHub/v-accordion$ 
zensey@pc:~/IdeaProjects/GitHub/v-accordion/node_modules/node-sass$ npm install -g
```

My environment:
iojs 3.3.0
ubuntu 15.10
libsass0 3.5.2
libsass-dev 3.5.2

I get the same result in MS Windows with node.js v4.2 on board

How to fix (at least in Ubuntu it helps)
```
npm uninstall --save-dev gulp-sass
npm install --save-dev gulp-sass@2
```

**Comment by LukaszWatroba** [comment]
Thanks @Zensey! Fixed.
